// <auto-generated />
using System;
using Baza.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Baza.Migrations
{
    [DbContext(typeof(LukaContext))]
    [Migration("20210118223035_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Baza.Models.Brod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("BrojUpotrebljivihKontejnera")
                        .HasColumnType("int")
                        .HasColumnName("BrojUpotrebljivihKontejnera");

                    b.Property<int?>("LukaID")
                        .HasColumnType("int");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MaxKapacitet");

                    b.Property<int>("TrenutnaZauzetost")
                        .HasColumnType("int")
                        .HasColumnName("TrenutnaZauzetost");

                    b.HasKey("ID");

                    b.HasIndex("LukaID");

                    b.ToTable("Brod");
                });

            modelBuilder.Entity("Baza.Models.Kontejner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("BrodID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Oznaka");

                    b.Property<int>("Tezina")
                        .HasColumnType("int")
                        .HasColumnName("Tezina");

                    b.HasKey("ID");

                    b.HasIndex("BrodID");

                    b.ToTable("Kontejner");
                });

            modelBuilder.Entity("Baza.Models.Luka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.HasKey("ID");

                    b.ToTable("Luka");
                });

            modelBuilder.Entity("Baza.Models.Brod", b =>
                {
                    b.HasOne("Baza.Models.Luka", "Luka")
                        .WithMany("Brodovi")
                        .HasForeignKey("LukaID");

                    b.Navigation("Luka");
                });

            modelBuilder.Entity("Baza.Models.Kontejner", b =>
                {
                    b.HasOne("Baza.Models.Brod", "Brod")
                        .WithMany("Kontejneri")
                        .HasForeignKey("BrodID");

                    b.Navigation("Brod");
                });

            modelBuilder.Entity("Baza.Models.Brod", b =>
                {
                    b.Navigation("Kontejneri");
                });

            modelBuilder.Entity("Baza.Models.Luka", b =>
                {
                    b.Navigation("Brodovi");
                });
#pragma warning restore 612, 618
        }
    }
}
